addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - xpra

language: node_js

node_js:
  - 5
  - 4

os:
  - linux

env:
  global:
    - CC=gcc-5 CXX=g++-5 DISPLAY=:99
  matrix:
    - WORKING_DIR=.
    - WORKING_DIR=e2e/mini/
    - WORKING_DIR=e2e/maxi/

before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install -y google-chrome-stable
  - xpra start :99
  - npm config set progress false
  - npm install -g npm@latest
  - cd $WORKING_DIR

script:
  - ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: piotr.baranowski@zaklinaczekodu.com
  api_key: $NPM_API_KEY
  on:
    node: 5
    condition: $WORKING_DIR == .
    tags: true
    repo: zaklinaczekodu/zkflow-angular
