addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - xpra
      - dbus-x11

language: node_js

node_js:
  - 5
  - 4
  - 0.12
  - 0.10

os:
  - linux

env:
  global:
    - CC=gcc-4.9 CXX=g++-4.9
  matrix:
    - WORKING_DIR=.
    - WORKING_DIR=e2e/mini/
    - WORKING_DIR=e2e/maxi/

before_install:
  - xpra start :99
  - npm update -g npm
  - cd $WORKING_DIR

script:
  - ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: bolczyslaw@gmail.com
  api_key: $npmApiKey
  on:
    node: 5
    condition: WORKING_DIR=.
    tags: true
    repo: zaklinaczekodu/gulp-zkflow-angular
