sudo: required
dist: trusty

addons:
  apt:
    packages:
      - dbus-x11

language: node_js

node_js:
  - 6
  - 5
  - 4

os:
  - linux

env:
  global:
    - DISPLAY=:99
  matrix:
    - WORKING_DIR=.
    - WORKING_DIR=e2e/mini/
    - WORKING_DIR=e2e/maxi/

before_install:
  - |
    npm install -g npm@latest
    cd $WORKING_DIR
    if [ $WORKING_DIR != . ]; then
      sudo apt-get update
      sudo apt-get install -yq --no-install-suggests --no-install-recommends --force-yes xpra
      xpra start :99
    fi

script:
  - dbus-launch --exit-with-session ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: piotr.baranowski@zaklinaczekodu.com
  api_key: $NPM_API_KEY
  on:
    node: 5
    condition: $WORKING_DIR == .
    tags: true
    repo: refilljs/refill-angular
