addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - xpra

language: node_js

node_js:
  - 5
  - 4

os:
  - linux

env:
  global:
    - CC=gcc-5 CXX=g++-5 DISPLAY=:99
  matrix:
    - WORKING_DIR=.
    - WORKING_DIR=e2e/mini/
    - WORKING_DIR=e2e/maxi/

before_install:
  - xpra start :99
  - npm config set progress false
  - npm install -g npm@latest
  - cd $WORKING_DIR

script:
  - ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: piotr.baranowski@zaklinaczekodu.com
  api_key: $NPM_API_KEY
  on:
    node: 5
    condition: $WORKING_DIR == .
    tags: true
    repo: zaklinaczekodu/zkflow-angular
