addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - xpra
      - dbus-x11

language: node_js

node_js:
  - 0.10
  - 0.12
  - iojs
  - 4
  - 5

os:
  - linux
#  - osx

env:
  global:
    - CC=gcc-4.9 CXX=g++-4.9
  matrix:
    - WORKING_DIR=.
    - WORKING_DIR=e2e/mini/

#matrix:
#  fast_finish: true
#  allow_failures:
#    - node_js: 4

before_install:
  - xpra start :99
  - npm update -g npm
  - cd $WORKING_DIR

script:
  - ./node_modules/.bin/gulp ci

deploy:
  provider: npm
  email: bolczyslaw@gmail.com
  api_key: $npmApiKey
  on:
    tags: true
    repo: zaklinaczekodu/gulp-zkflow-angular